baseURL = "https://nahuumm.github.io/portafolio-/"
languageCode = "es-mx"
title = "Diego Nahum | Portafolio"
theme = "gokarna"

[params]
  description = "Portafolio de prácticas - Paradigmas de la Programación | UABC"
  showPostsOnHomePage = "all"
  footer = "Diego Nahum Nuñez García · UABC 2026"
  metaKeywords = ["portfolio", "haskell", "programacion", "uabc"]
  enableGitalk = false

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Prácticas"
    url = "/posts/"
    weight = 2